name: shell_cmd
description: A library for running programs either explicitly or in shell
version: 0.2.2
repository: https://github.com/aiurovet/shell_cmd/

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  charcode: ^1.3.1
  path: ^1.8.2
  string_scanner: ^1.2.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.24.1
